language: julia

os:
  - linux

branches:
  only:
  - master

addons:
  apt:
    update: true

julia:
  - 0.6
  - 0.7

notifications:
  email: false

# before_script:
#  - curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash
#  - cd $TRAVIS_BUILD_DIR && fossa
  
after_success:
  - julia -e 'cd(Pkg.dir("Triangle")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  - cd $TRAVIS_BUILD_DIR && julia -e 'Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'  

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/build
  on:
    branch: master
